export const dataProperties = [
  {
    id: 1,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 2,
    location: "Reforma, Navojoa, Son.",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 3,
    location: "Reforma, Navojoa, Son.",
    price: 35.0,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 5,
    meters: 90,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 4,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpeg",
    star: 4.2,
    meters: 120,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 5,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpeg",
    star: 4.1,
    meters: 87,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 6,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 7,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 8,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 9,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 380,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 10,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 11,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 12,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 13,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 14,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 15,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 16,
    location: "Reforma, Navojoa, Son.",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Reforma, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
];
